### ISSUE TITLE
Spaces are not handled well for file upload/download

### ISSUE THREAD

**Issue by willief** [maidsafe/autonomi#1145] opened 2024-01-06 00:32 UTC
It was noticed in the forum 
https://safenetforum.org/t/newyearnewnet-04-01-2024-testnet/39034/156?u=southside https://safenetforum.org/t/newyearnewnet-04-01-2024-testnet/39034/169?u=southside

that uploads with spaces in the file name tend to fail whilst the same file uploaded with a filename not containing spaces work as expected.
Credit to @nos for noticing this

**Comment by JasonPaulGithub** [comment] 2024-02-28 13:54
I have failed to recreate this bug. A file with spaces in the name was uploaded and downloaded without issue.
Is this bug still an issue? If so perhaps I can take a closer look.

**Comment by JasonPaulGithub** [comment] 2024-02-28 14:02
@willief @joshuef
I have failed to recreate this bug. A file with spaces in the name can be uploaded and downloaded.
Is this bug still an issue? If so perhaps I can take a closer look.

**Comment by joshuef** [comment] 2024-03-05 23:16
Closing this as we cannot reproduce. Please reopen @willief if you're still able to do so.

**Closed as completed by joshuef** 2024-03-05 23:16 UTC
Labels: Bug
